### PR TITLE
3.13.2

### PR DESCRIPTION
**Pull request by hmaarrfk**
Fixes: https://github.com/conda-forge/json_tricks-feedstock/pulls
And asked upstream to include license file in their distribution: https://github.com/mverleg/pyjson_tricks/pull/61
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge/json_tricks this is ready for review.

**Review by jhkennedy — COMMENTED** [review]
Sorry @hmaarrfk I didn't get a GH notification for this. 

Mostly looks good, but there is a `3.13.4` version out on PyPi -- do you need `3.13.2` in conda-forge (I know json-tricks allows api breaking changes in any version, so it's possible you do)?

**Comment by hmaarrfk** [comment]
Not really, I just wanted an updated version

**Comment by jhkennedy** [comment]
@hmaarrfk sounds good, I'll bump it to 3.13.4 and merge it in about an hour and a half (once I get out of meeting).

**Comment by hmaarrfk** [comment]
The big did most of the heavy lifting

https://github.com/conda-forge/json_tricks-feedstock/pull/8

**Comment by hmaarrfk** [comment]
Bot

**Comment by jhkennedy** [comment]
:+1: (I gotta figure out why PR notifications aren't coming through for this repo...)

**Pull request closed without merging**
